VERSION: 1.10.0
CONFIGURATION: Release
NUGETPACKAGES:
  - TestUtilities:
    Name: Calot.TestUtilities
    Version: 1.10.0
    Location: src/Thuria.Calot.TestUtilities
    IsBeta: false
    Frameworks:
      - net461
      - net472
      - net48
      - netstandard2.0
      - net6
      - net7.0
      - net8.0
