VERSION: 1.2.1
CONFIGURATION: Release
NUGETPACKAGES:
  - TestUtilities:
    Name: Calot.TestUtilities
    Version: 1.2.1
    Location: src/Thuria.Calot.TestUtilities
    IsBeta: false
    Frameworks:
      - net461
      - net472
      - netstandard2.0
      - netcoreapp3.0
