VERSION: 1.3.0
CONFIGURATION: Release
NUGETPACKAGES:
  - TestUtilities:
    Name: Calot.TestUtilities
    Version: 1.3.0
    Location: src/Thuria.Calot.TestUtilities
    IsBeta: false
    Frameworks:
      - net461
      - net472
      - net48
      - netstandard2.0
      - netcoreapp3.0
