# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    # linux:
    #   imageName: "ubuntu-16.04"
    windows:
      imageName: "vs2017-win2016"
  maxParallel: 2

pool:
  vmImage: $(imageName)

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Install dotnet core 2.1.300'
  inputs:
    version: '2.2.300'
    
- script: npm install

- task: DownloadSecureFile@1
  displayName: 'Download NuGet Settings'
  inputs:
    secureFile: 'nugetSettings.yml'

- task: Npm@1
  displayName: 'Building project'
  inputs:
    command: 'custom'
    customCommand: 'run build'
    
- task: DotNetCoreCLI@2
  displayName: 'Executing tests'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --logger trx --collect "Code Coverage" --output buildoutput/testResults'

- task: PublishTestResults@2
  displayName:  'Publish Test Results'
  inputs:
    testRunner: VSTest
    testResultsFiles: 'buildoutput/testResults/*.trx'
  